### ISSUE TITLE
Deployment script failed at set Set-SqlServerAADAdministrator

### ISSUE THREAD

**Issue by rick-ji** [microsoft/Nonprofit_Data_Warehouse_Quickstart#1]
The deployment scripted failed at runing Set-SqlServerAADAdministrator, i've received below error

### Script Executed with Errors - DeployOrchestrator
C:\src\NonprofitDataWarehouseQuickstart\Deployment\Scripts\Set-SqlServerAADAdministrator.ps1 : Cannot validate argument on parameter 'SqlServerAdmin'. 
The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\src\NonprofitDataWarehouseQuickstart\Deployment\DeployOrchestrator.ps1:239 char:25
+         -SqlServerAdmin $AdminGroupName;
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-SqlServerAADAdministrator.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Set-SqlServerAADAdministrator.ps1

**Comment by elucht** [comment]
Under investigation.

**Comment by elucht** [comment]
This was resolved by clarification of documentation and deployment orchestration script parameters.  Thank you for your input!
