### ISSUE TITLE
Post deployment DW table pupulation, the tables are not exist from deployment script

### ISSUE THREAD

**Issue by rick-ji** [microsoft/Nonprofit_Data_Warehouse_Quickstart#2]
I've followed the instruction, the deployment finished but we some error in the last few steps. But ihave manually updated those on azure portal and updated source data to storage account. But the SQL DW(Synapse) instance doesn't have any table from the deployment. The post deploy script won't work

i.e Msg 15165, Level 16, State 1, Line 1
Could not find object 'Control' or you do not have permission.

There isn't a Control table created from deployment script

**Comment by elucht** [comment]
Under investigation.

**Comment by elucht** [comment]
This was resolved by clarification of documentation and deployment orchestration script parameters.  Thank you for your input!
